# Generated by Django 4.2.11 on 2024-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_company_company_id_remove_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Cost_To_Company',
            field=models.IntegerField(null=True),
        ),
    ]
