# Generated by Django 4.2.11 on 2024-06-11 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.TimeField(auto_now_add=True)),
                ('acknowledged_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Rejected'), ('A', 'Accepted'), ('N', 'Not yet acknowledged')], default='N', max_length=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
